<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTwoLastArticles()
    {
        return $this->createQueryBuilder('b')
            ->orderBy('b.publicationDate', 'DESC')
            ->setMaxResults(2)
            ->getQuery()
            ->getResult();
    }

    public function sortArticlesByDate()
    {
        return $this->createQueryBuilder('b')
            ->orderBy('b.publicationDate', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
